### ISSUE TITLE
fresh install segfault

### ISSUE THREAD

**Issue by LeSpatiocorne** [escapingnetwork/core-keeper-dedicated#58]
I've got a segfault on fresh install and can't even launch properly the server.
At first, I thought that was because of the host install I was using, so I tried a local install but got the exact same result !
```
steam user is not set.
Using anonymous user.
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
Logging directory: '/home/container/Steam/logs'
[ 0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1726605427
-- type 'quit' to exit --
Loading Steam API...OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '1007' already up to date.
Success! App '1963720' already up to date.
:/home/container$ export DISPLAY=:0; rm ./GameID.txt ./CoreKeeperServerLog.txt; touch ./CoreKeeperServerLog.txt; xvfb-run -s "-screen 0 ${DISPLAY_WIDTH}x${DISPLAY_HEIGHT}x${DISPLAY_DEPTH} -ac -nolisten tcp -nolisten unix" ./CoreKeeperServer -batchmode -logfile CoreKeeperServerLog.txt -world ${WORLD_INDEX} -worldname "${WORLD_NAME}" -worldseed ${WORLD_SEED} $([[ "${GAME_ID}" != "" ]] && echo -n " -gameid ${GAME_ID}") -maxplayers ${MAX_PLAYERS} -worldmode ${WORLD_MODE} -port ${SERVER_PORT} & CKPID=$!; tail -f CoreKeeperServerLog.txt | grep -e '^\[userid:[0-9]*\] player' -e '^[^\[]' & LOGPID=$!; trap "kill ${CKPID}; wait ${CKPID}; kill ${LOGPID}; wait ${LOGPID}" 15; wait $!
rm: cannot remove './GameID.txt': No such file or directory
[UnityMemory] Configuration Parameters - Can be set up in boot.config
"memorysetup-bucket-allocator-granularity=16"
"memorysetup-bucket-allocator-bucket-count=8"
"memorysetup-bucket-allocator-block-size=4194304"
"memorysetup-bucket-allocator-block-count=1"
"memorysetup-main-allocator-block-size=16777216"
"memorysetup-thread-allocator-block-size=16777216"
"memorysetup-gfx-main-allocator-block-size=16777216"
"memorysetup-gfx-thread-allocator-block-size=16777216"
"memorysetup-cache-allocator-block-size=4194304"
"memorysetup-typetree-allocator-block-size=2097152"
"memorysetup-profiler-bucket-allocator-granularity=16"
"memorysetup-profiler-bucket-allocator-bucket-count=8"
"memorysetup-profiler-bucket-allocator-block-size=4194304"
"memorysetup-profiler-bucket-allocator-block-count=1"
"memorysetup-profiler-allocator-block-size=16777216"
"memorysetup-profiler-editor-allocator-block-size=1048576"
"memorysetup-temp-allocator-size-main=4194304"
"memorysetup-job-temp-allocator-block-size=2097152"
"memorysetup-job-temp-allocator-block-size-background=1048576"
"memorysetup-job-temp-allocator-reduction-small-platforms=262144"
"memorysetup-allocator-temp-initial-block-size-main=262144"
"memorysetup-allocator-temp-initial-block-size-worker=262144"
"memorysetup-temp-allocator-size-background-worker=32768"
"memorysetup-temp-allocator-size-job-worker=262144"
"memorysetup-temp-allocator-size-preload-manager=262144"
"memorysetup-temp-allocator-size-nav-mesh-worker=65536"
"memorysetup-temp-allocator-size-audio-worker=65536"
"memorysetup-temp-allocator-size-cloud-worker=32768"
"memorysetup-temp-allocator-size-gfx=262144"
Mono path[0] = '/home/container/CoreKeeperServer_Data/Managed'
Mono config path = '/home/container/CoreKeeperServer_Data/MonoBleedingEdge/etc'
Preloaded 'discord_game_sdk.so'
Shutdown handler: initialize.
Preloaded 'libEOSSDK-Linux-Shipping.so'
Preloaded 'libPlayFabMultiplayer.so'
Preloaded 'lib_burst_generated.so'
Caught fatal signal - signo:11 code:1 errno:0 addr:0x20
Obtained 24 stack frames.
#0 0x007f02e445b050 in __sigaction
#1 0x007f023edf6ee0 in BumblelionLogger::TryToLoadConfigurationFile()
#2 0x007f023edf6cd8 in BumblelionLogger::BumblelionLogger()
#3 0x007f023edf7870 in BumblelionLogger::GetInstance()
#4 0x007f023edf6bf6 in DbgLogAreaFlags_FnInOut
#5 0x007f023ee0ed79 in OutstandingPlayFabRequestManager::OutstandingRequest::OutstandingRequest()
#6 0x007f023ee0ebfd in OutstandingPlayFabRequestManager::OutstandingRequestList::OutstandingRequestList()
#7 0x007f023ee146ab in _GLOBAL__sub_I_PlayFabServiceManagerImpl.cpp
#8 0x007f02e68679ce in __nptl_change_stack_perm
#9 0x007f02e6867ab4 in __nptl_change_stack_perm
#10 0x007f02e456e024 in _dl_catch_exception
#11 0x007f02e686e21e in _dl_rtld_di_serinfo
#12 0x007f02e456dfca in _dl_catch_exception
#13 0x007f02e686e5b8 in _dl_find_dso_for_object
#14 0x007f02e44a4438 in dlmopen
#15 0x007f02e456dfca in _dl_catch_exception
#16 0x007f02e456e07f in _dl_catch_error
#17 0x007f02e44a3f27 in dlerror
#18 0x007f02e44a44e9 in dlopen
#19 0x007f02e546df8e in PlayerMain(int, char**)
#20 0x007f02e545e77d in PlayerMain(int, char**)
#21 0x007f02e444624a in __libc_init_first
#22 0x007f02e4446305 in __libc_start_main
#23 0x00000000201029 in (Unknown)
Segmentation fault (core dumped)
steam user is not set.
Using anonymous user.
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
Logging directory: '/home/container/Steam/logs'
[ 0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1726605427
-- type 'quit' to exit --
Loading Steam API...OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '1007' already up to date.
Success! App '1963720' already up to date.
:/home/container$ export DISPLAY=:0; rm ./GameID.txt ./CoreKeeperServerLog.txt; touch ./CoreKeeperServerLog.txt; xvfb-run -s "-screen 0 ${DISPLAY_WIDTH}x${DISPLAY_HEIGHT}x${DISPLAY_DEPTH} -ac -nolisten tcp -nolisten unix" ./CoreKeeperServer -batchmode -logfile CoreKeeperServerLog.txt -world ${WORLD_INDEX} -worldname "${WORLD_NAME}" -worldseed ${WORLD_SEED} $([[ "${GAME_ID}" != "" ]] && echo -n " -gameid ${GAME_ID}") -maxplayers ${MAX_PLAYERS} -worldmode ${WORLD_MODE} -port ${SERVER_PORT} & CKPID=$!; tail -f CoreKeeperServerLog.txt | grep -e '^\[userid:[0-9]*\] player' -e '^[^\[]' & LOGPID=$!; trap "kill ${CKPID}; wait ${CKPID}; kill ${LOGPID}; wait ${LOGPID}" 15; wait $!
rm: cannot remove './GameID.txt': No such file or directory
[UnityMemory] Configuration Parameters - Can be set up in boot.config
"memorysetup-bucket-allocator-granularity=16"
"memorysetup-bucket-allocator-bucket-count=8"
"memorysetup-bucket-allocator-block-size=4194304"
"memorysetup-bucket-allocator-block-count=1"
"memorysetup-main-allocator-block-size=16777216"
"memorysetup-thread-allocator-block-size=16777216"
"memorysetup-gfx-main-allocator-block-size=16777216"
"memorysetup-gfx-thread-allocator-block-size=16777216"
"memorysetup-cache-allocator-block-size=4194304"
"memorysetup-typetree-allocator-block-size=2097152"
"memorysetup-profiler-bucket-allocator-granularity=16"
"memorysetup-profiler-bucket-allocator-bucket-count=8"
"memorysetup-profiler-bucket-allocator-block-size=4194304"
"memorysetup-profiler-bucket-allocator-block-count=1"
"memorysetup-profiler-allocator-block-size=16777216"
"memorysetup-profiler-editor-allocator-block-size=1048576"
"memorysetup-temp-allocator-size-main=4194304"
"memorysetup-job-temp-allocator-block-size=2097152"
"memorysetup-job-temp-allocator-block-size-background=1048576"
"memorysetup-job-temp-allocator-reduction-small-platforms=262144"
"memorysetup-allocator-temp-initial-block-size-main=262144"
"memorysetup-allocator-temp-initial-block-size-worker=262144"
"memorysetup-temp-allocator-size-background-worker=32768"
"memorysetup-temp-allocator-size-job-worker=262144"
"memorysetup-temp-allocator-size-preload-manager=262144"
"memorysetup-temp-allocator-size-nav-mesh-worker=65536"
"memorysetup-temp-allocator-size-audio-worker=65536"
"memorysetup-temp-allocator-size-cloud-worker=32768"
"memorysetup-temp-allocator-size-gfx=262144"
Mono path[0] = '/home/container/CoreKeeperServer_Data/Managed'
Mono config path = '/home/container/CoreKeeperServer_Data/MonoBleedingEdge/etc'
Preloaded 'discord_game_sdk.so'
Shutdown handler: initialize.
Preloaded 'libEOSSDK-Linux-Shipping.so'
Preloaded 'libPlayFabMultiplayer.so'
Preloaded 'lib_burst_generated.so'
Caught fatal signal - signo:11 code:1 errno:0 addr:0x20
Obtained 24 stack frames.
#0 0x007f02e445b050 in __sigaction
#1 0x007f023edf6ee0 in BumblelionLogger::TryToLoadConfigurationFile()
#2 0x007f023edf6cd8 in BumblelionLogger::BumblelionLogger()
#3 0x007f023edf7870 in BumblelionLogger::GetInstance()
#4 0x007f023edf6bf6 in DbgLogAreaFlags_FnInOut
#5 0x007f023ee0ed79 in OutstandingPlayFabRequestManager::OutstandingRequest::OutstandingRequest()
#6 0x007f023ee0ebfd in OutstandingPlayFabRequestManager::OutstandingRequestList::OutstandingRequestList()
#7 0x007f023ee146ab in _GLOBAL__sub_I_PlayFabServiceManagerImpl.cpp
#8 0x007f02e68679ce in __nptl_change_stack_perm
#9 0x007f02e6867ab4 in __nptl_change_stack_perm
#10 0x007f02e456e024 in _dl_catch_exception
#11 0x007f02e686e21e in _dl_rtld_di_serinfo
#12 0x007f02e456dfca in _dl_catch_exception
#13 0x007f02e686e5b8 in _dl_find_dso_for_object
#14 0x007f02e44a4438 in dlmopen
#15 0x007f02e456dfca in _dl_catch_exception
#16 0x007f02e456e07f in _dl_catch_error
#17 0x007f02e44a3f27 in dlerror
#18 0x007f02e44a44e9 in dlopen
#19 0x007f02e546df8e in PlayerMain(int, char**)
#20 0x007f02e545e77d in PlayerMain(int, char**)
#21 0x007f02e444624a in __libc_init_first
#22 0x007f02e4446305 in __libc_start_main
#23 0x00000000201029 in (Unknown)
Segmentation fault (core dumped)
```

**Comment by avatar7008** [comment]
Find and delete the libparty.so file from CoreKeeperServer_Data/Plugins.

Saw it on a reddit thread somewhere and it works.
